version: "3.8"

services:
  localstack:
    container_name: "localaws_localstack"
    image: localstack/localstack:1.3.1
    ports:
      - "127.0.0.1:8566:4566"            # LocalStack Gateway
      - "127.0.0.1:8510-8559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "./docker.sock:/var/run/docker.sock"